<?xml version="1.0"?>
<package format="3">
  <name>turtlebot_description</name>
  <version>1.0.0</version>
  <description>Description of TurtleBot</description>
  
  <maintainer email="user@example.com">Your Name</maintainer>
  <license>BSD</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  
  <depend>urdf</depend>
  <depend>xacro</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>